# Generated by Django 5.1.3 on 2024-12-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Unsolved', 'Unsolved'), ('Attempted', 'Attempted'), ('Solved', 'Solved')], default='Unsolved', max_length=50)),
            ],
        ),
    ]
