# Generated by Django 5.1.3 on 2024-12-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_question_difficulty_alter_question_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
    ]
