# Generated by Django 5.1.3 on 2024-12-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
