# Generated by Django 5.1.3 on 2024-12-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_token_consumption_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='token_consumed_today',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
