# Generated by Django 5.1.3 on 2024-12-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_last_token_consumption_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='no_of_easy_problems_solved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='no_of_hard_problems_solved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='no_of_medium_problems_solved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_problems_solved',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
