# Generated by Django 5.1.3 on 2024-12-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userprofile_no_of_easy_problems_solved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='session_time',
            field=models.IntegerField(default=0),
        ),
    ]
