# Generated by Django 5.1.3 on 2024-12-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile_last_active_userprofile_session_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_time_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_reset',
            field=models.DateField(auto_now_add=True, default='2024-12-13'),
            preserve_default=False,
        ),
    ]
