# Generated by Django 5.1.3 on 2025-01-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_userprofile_education_hsc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp_key',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
    ]
