# Generated by Django 5.1.3 on 2025-01-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_otp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token_limit',
            field=models.PositiveIntegerField(default=20000),
        ),
    ]
