# Generated by Django 5.1.5 on 2025-02-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='companies',
            field=models.TextField(null=True),
        ),
    ]
