# Generated by Django 5.1.5 on 2025-02-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_question_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionstatus',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
