# Generated by Django 5.1.3 on 2025-03-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_userquestionstatus_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='no_of_c_problems_solved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='no_of_cpp_problems_solved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='no_of_csharp_problems_solved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='no_of_go_problems_solved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='no_of_java_problems_solved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='no_of_javascript_problems_solved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='no_of_php_problems_solved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='no_of_python_problems_solved',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
